#!/bin/bash

FILES=".bashrc .bash_profile .commonrc .vimrc .vim"

function install () {
    mkdir -p .vim/backup

    echo "Installing plugins"

    # Install pathogen
    mkdir -p .vim/autoload .vim/bundle
    curl -LSso .vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    git submodule init
    git submodule update

    echo "Installing symbolic links"
    for FILE in $FILES; do
        if [ -e ~/$FILE ]; then
            echo "~/$FILE already exists, skipping..."
        else
            ln -vs $PWD/$FILE ~/$FILE
        fi
    done
}

function update() {
    git pull
    git submodule init
    git submodule update
}

function uninstall () {
    echo "Uninstalling symbolic links"
    for FILE in $FILES; do
        if [ -L ~/$FILE ]; then
            rm -v ~/$FILE
        else
            echo "~/$FILE is not a symbolic link, skipping..."
        fi
    done

    # Uninstall pathogen
    rm .vim/autoload/pathogen.vim
}

function help() {
    echo "Usage:"
    echo "$0 action"
    echo ""
    echo "Actions:"
    echo "   install"
    echo "   update"
    echo "   uninstall"
}

function main() {
    case "$1" in
        install) install ;;
        update) update ;;
        uninstall) uninstall ;;
        *) help ;;
    esac
}

main $*

