#!/bin/bash

FILES=".bashrc .bash_profile .vimrc .vim"
PATHOGEN_URL="https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"

function download_to () {
    echo "Downloading $1 -> $2"
    WGET="`which wget`"
    if [ $? -eq 0 ]; then
        ${WGET} -O "$2" "$1" >/dev/null 2>&1
        return $?
    fi
    CURL="`which curl`"
    if [ $? -eq 0 ]; then
        ${CURL} -o "$2" "$1" >/dev/null 2>&1
        return $?
    fi
    return 1
}

function install () {
    mkdir -p .vim/{backup,colors,autoload}

    echo "Installing plugins"

    # install pathogen

    PATHOGEN_LOCAL_PATH=".vim/autoload/pathogen.vim"
    if [ -e "${PATHOGEN_LOCAL_PATH}" ]; then
        echo "Pathogen plugin already installed, skipping..."
    else
        download_to "${PATHOGEN_URL}" "${PATHOGEN_LOCAL_PATH}"
    fi

    # install other plugins
    git submodule init
    git submodule update

    echo "Installing symbolic links"
    for FILE in $FILES; do
        if [ -e ~/$FILE ]; then
            echo "~/$FILE already exists, skipping..."
        else
            ln -vs $PWD/$FILE ~/$FILE
        fi
    done
}

function uninstall () {
    echo "Uninstalling symbolic links"
    for FILE in $FILES; do
        if [ -L ~/$FILE ]; then
            rm -v ~/$FILE
        else
            echo "~/$FILE is not a symbolic link, skipping..."
        fi
    done
}

function help() {
    echo "Usage:"
    echo "$0 action"
    echo ""
    echo "Actions:"
    echo "   install"
    echo "   uninstall"
}

function main() {
    case "$1" in
        install) install ;;
        uninstall) uninstall ;;
        *) help ;;
    esac
}

main $*

